### ISSUE TITLE
Can useConstructor be supported?

### ISSUE THREAD

**Issue by hzeroo** [pveyes/use-less#1]
Could this be possible? 

```
const [state, setState] = useConstructor(initialState);
```

That would not just allow to use constructor, but would make it easier to use a single state for the whole component, avoiding the whole mess of having to declare more than one state.

:)

**Comment by pveyes** [comment]
Hi, thank you for the idea. My implementation is different than what you proposed here, but it's closer to how we used to set initial state in react (assigning state to `this`).

You can see in the linked PR there, let me know what you think!

**Comment by hzeroo** [comment]
Brilliant!
